export { default as Home } from "./Home/Home"
export { default as Contact } from "./Contact/Contact"
export { default as Cart } from "./Cart/Cart"
export { default as Admin } from "./Admin/Admin"
export { default as OrderHistory } from "./OrderHistory/OrderHistory"